version: 0.0
os: linux
files:
  - source: AspNetCoreWebApplication/build_output
    destination: /home/ubuntu/aspnetcoreapp
  - source: scripts/virtualhost.conf
    destination: /home/ubuntu/aspnetcoreapp
  - source: scripts/kestrel-aspnetcoreapp.service
    destination: /etc/systemd/system/
    
overwrite: true
permissions:
- object: /var/www/html/test-deploy/codedeploy
pattern: "*.sh"
owner: root
group: root
mode: 755
type:
- file
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dotnetcore
      timeout: 500
      runas: root

    - location: scripts/install_httpd
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
