version: 0.0
os: linux
files:
  - source: AspNetCoreWebApplication/build_output
    destination: /var/www/web
  - source: scripts/virtualhost.conf
    destination: /home/ec2-user/aspnetcoreapp
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dotnetcore
      timeout: 500
      runas: root

    - location: scripts/install_httpd
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
